import Head from 'next/head'
import Header from '../components/Header';
import Footer from '../components/Footer';
import Main from '../components/Main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google|Giorgi Gobechia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {/* Header */}  
    <Header/>
    {/* Body */}  
   <Main/>
    {/* Footer */}  
   <Footer/>
    </div>
  )
}
